ShoppingMall/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls.static import static
from ShoppingMall import settings

from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^tinymce/', include('tinymce.urls')),  # 富文本编辑器
    path('user/', include(('apps.user.urls', 'apps.user'), namespace='user')),    # 用户模块
    path('cart/', include(('apps.cart.urls', 'apps.cart'), namespace='cart')),     # 购物车模块
    path('order/', include(('apps.order.urls', 'apps.order'), namespace='order')),   # 订单模块
    re_path('', include(('apps.goods.urls', 'apps.goods'), namespace='goods')),   # 商品模块

    re_path(r'^favicon.ico$', RedirectView.as_view(url=r'/static/favicon.ico', permanent=True)),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# 超级用户：root   密码：root123456
# 普通用户的用户名密码设计：user1, user1123 ; user2, user2123

apps/cart/urls.py
#_*_coding:utf-8_*_


from django.urls import path, re_path
from apps.cart import views

urlpatterns = [
    re_path(r'^$', views.CartInfoView.as_view(), name='show'),  # 购物车页面

    path('add', views.CartAddView.as_view(), name='add'),
    # path(r'update', views.CartUpdateView.as_view(), name='update'), # 修改购物车中的商品记录
    path(r'delete', views.CartDeleteView.as_view(), name='delete'), # 删除购物车中的商品记录
]

apps/goods/urls.py
#_*_coding:utf-8_*_


from django.urls import path, re_path
from apps.goods import views

urlpatterns = [
    path('index/', views.IndexView.as_view(), name='index'),   # 用户注册页面
    re_path(r'^goods/(?P<goods_id>\d+)$', views.DetailView.as_view(), name='detail'),  # 详情页
    re_path(r'list/(?P<type_id>\d+)/(?P<page>\d+)', views.ListView.as_view(), name='list'),  # 列表页
    re_path(r'search/(?P<page>\d+)', views.SearchView.as_view(), name='search'),
]

apps/user/urls.py
from django.urls import path, re_path
from apps.user import views


urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),   # 用户注册页面
    path('login/', views.LoginView.as_view(), name='login'),   # 用户注册页面
    re_path('active/(?P<token>.*)$', views.ActiveView.as_view(), name='active'),   # 用户账号激活路由
    path('logout/', views.LogoutView.as_view(), name='logout'),   # 用户注销登录路由

    re_path(r'^$', views.UserInfoView.as_view(), name='users'),  # 用户中心-信息页
    re_path(r'^order/(?P<page>\d+)$', views.UserOrderView.as_view(), name='order'),  # 用户中心-订单页
    path(r'address/', views.AddressView.as_view(), name='address'),  # 用户中心-地址页

    path(r'get_valid_img/', views.get_valid_img),

]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/order/models.py
from django.db import models
from db.base_model import BaseModel


class OrderInfo(BaseModel):
    '''订单模型类'''

    ORDER_STATUS = {
        1: '待支付',
        2: '待发货',
        3: '待收货',
        4: '待评价',
        5: '已完成'
    }

    PAY_METHOD_CHOICES = (
        (1, '货到付款'),
        (2, '微信支付'),
        (3, '支付宝'),
        (4, '银联支付')
    )

    ORDER_STATUS_CHOICES = (
        (1, '待支付'),
        (2, '待发货'),
        (3, '待收货'),
        (4, '待评价'),
        (5, '已完成')
    )

    order_id = models.CharField(max_length=128, primary_key=True, verbose_name='订单id')
    user = models.ForeignKey('user.User', on_delete='CASCADE', verbose_name='用户')
    addr = models.ForeignKey('user.Address', on_delete='CASCADE', verbose_name='地址')
    pay_method = models.SmallIntegerField(choices=PAY_METHOD_CHOICES, default=3, verbose_name='支付方式')
    total_count = models.IntegerField(default=1, verbose_name='商品数量')
    total_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品总价')
    transit_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='订单运费')
    order_status = models.SmallIntegerField(choices=ORDER_STATUS_CHOICES, default=1, verbose_name='订单状态')
    trade_no = models.CharField(max_length=128, default='', verbose_name='支付编号')

    class Meta:
        db_table = 'df_order_info'
        verbose_name = '订单'
        verbose_name_plural = verbose_name


class OrderGoods(BaseModel):
    '''订单商品模型类'''
    order = models.ForeignKey('OrderInfo', on_delete='CASCADE', verbose_name='订单')
    sku = models.ForeignKey('goods.GoodsSKU', on_delete='CASCADE', verbose_name='商品SKU')
    count = models.IntegerField(default=1, verbose_name='商品数目')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='商品价格')
    comment = models.CharField(max_length=256, default='', verbose_name='评论')

    class Meta:
        db_table = 'df_order_goods'
        verbose_name = '订单商品'
        verbose_name_plural = verbose_name

apps/cart/views.py
from django.shortcuts import render, redirect
from utils.mixin import LoginRequiredMixin
from django.views import View
from django_redis import get_redis_connection
from apps.goods.models import GoodsSKU
from django.http import JsonResponse


class CartInfoView(LoginRequiredMixin, View):
    '''购物车页面显示'''
    def get(self, request):
        '''显示'''
        user = request.user

        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        # hgetall()函数返回的结果为字典类型 {'商品id':商品数量}
        cart_dict = conn.hgetall(cart_key)

        skus = []
        # 保存用户购物车中商品的总数目和总价格
        total_price = 0
        total_count = 0
        for sku_id, count in cart_dict.items():
            # 根据商品的id获取商品的信息
            sku = GoodsSKU.objects.get(id=sku_id)
            # 计算商品的小计
            amount = sku.price*int(count)
            # 动态给sku对象增加一个属性amount, 保存商品的小计
            sku.amount = amount
            # 动态给sku对象增加一个属性count, 保存购物车中对应商品的数量
            sku.count = int(count)

            skus.append(sku)

            # 累加计算商品的总数目和总价格
            total_count += int(count)
            total_price += amount

        context = {
            'total_count': total_count,
            'total_price': total_price,
            'skus': skus,}

        return render(request, 'cart.html', context)


class CartAddView(View):
    """添加商品到购物车视图"""
    def post(self, request):
        user = request.user

        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        sku_id = request.POST.get('sku_id')
        count = request.POST.get("count")

        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目出错'})
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        cart_count = conn.hget(cart_key, sku_id)
        if cart_count:
            count += int(cart_count)

        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})
        # 设置hash中sku_id对应的值
        # hset方法：如果sku_id已经存在，更新数据， 如果sku_id不存在，添加数据
        conn.hset(cart_key, sku_id, count)
        # 计算用户购物车商品的条目数
        total_count = conn.hlen(cart_key)

        return JsonResponse({'res': 5, 'total_count': total_count, 'message': '添加成功'})


# 删除购物车记录
# 采用ajax post请求
# 前端需要传递的参数:商品的id(sku_id)
# /cart/delete
class CartDeleteView(View):
    '''购物车记录的删除'''
    def post(self, request):
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        sku_id = request.POST.get('sku_id')

        if not sku_id:
            return JsonResponse({'res': 1, 'errmsg': '无效的商品id'})
        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

        conn = get_redis_connection('default')
        cart_key = 'cart_%d'%user.id
        conn.hdel(cart_key, sku_id)

        # 计算用户购物车中商品的总件数
        total_count = 0
        vals = conn.hvals(cart_key)
        for val in vals:
            total_count += int(val)

        return JsonResponse({'res': 3, 'message': '删除成功', 'total_count': total_count})

templates/search.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-搜索结果列表</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜商城!</div>
			<div class="fr">
				{% if request.user.is_authenticated %}
                    <div class="login_info fl">
					欢迎您：<em>{{ request.user.username }}</em>
				    </div>

                    <div class="user_link fl">
                    <span>|</span>
					<a href="{% url 'goods:index' %}">回到首页</a>
					<span>|</span>
					<a href="{% url 'user:users' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出登录</a>
				</div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">登录</a>
                        <span>|</span>
                        <a href="{% url 'user:register' %}">注册</a>
				    </div>
                {% endif %}
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" id="search_keywords" name="keywords" placeholder="搜索商品" value="{{ keywords }}">
            <input type="button" class="input_btn fr" id="jsSearchBtn" name="search" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl">{{ cart_count }}</div>
		</div>
	</div>

	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>	
				<span></span>			
				<ul class="subnav">
					{% for type in types %}
                        <li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="{% url 'goods:index' %}">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="breadcrumb">
		<a href="{% url 'goods:index' %}">首页</a>
		<span>></span>
		<a href="#">搜索结果</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:search' 1 %}?keywords={{ keywords }}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:search' 1 %}?sort=price&keywords={{ keywords }}" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:search' 1 %}?sort=hot&keywords={{ keywords }}" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in skus_page %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">&nbsp;&nbsp;销量：{{ sku.sales }}</span>
						<a href="javascript:;" class="add_goods" id="add_cart" sku_id="{{ sku.id }}" title="加入购物车"></a>
                        {% csrf_token %}
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
                {% if skus_page.has_previous %}
				<a href="{% url 'goods:search' skus_page.previous_page_number %}?sort={{ sort }}&keywords={{ keywords }}"><上一页</a>
                {% endif %}
                {% for pindex in skus_page.paginator.page_range %}
                    {% if pindex == skus_page.number %}
				        <a href="{% url 'goods:search' pindex %}?sort={{ sort }}&keywords={{ keywords }}" class="active">{{ pindex }}</a>
                    {% else %}
				        <a href="{% url 'goods:search' pindex %}?sort={{ sort }}&keywords={{ keywords }}">{{ pindex }}</a>
                    {% endif %}
				{% endfor %}
                {% if skus_page.has_next %}
				<a href="{% url 'goods:search' skus_page.next_page_number %}?sort={{ sort }}&keywords={{ keywords }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>天天生鲜商城系统</p>
	</div>

    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/search.js' %}"></script>
    <script type="text/javascript">
        $('.add_goods').click(function(){
			// 获取商品id和商品数量
            sku_id = $(this).attr('sku_id');
            count = 1;
            csrf = $('input[name="csrfmiddlewaretoken"]').val();
            // 组织参数
            params = {'sku_id':sku_id, 'count':count, 'csrfmiddlewaretoken':csrf};
            // 发起ajax post请求，访问/cart/add, 传递参数:sku_id count
            $.ajax({
                url:'/cart/add',
                type:"POST",
                data:params,
                success:function (data) {
                    if (data.res == 5){
                        // 添加成功
                        alert("加入购物车成功~");
                        oldval = $('.goods_count')
                        count_all = parseInt(oldval.text())+1;
                        $('.goods_count').text(count_all)
                    }else{
                        // 添加失败
                        alert(data.errmsg)
                    }
                }
            });
		})
    </script>

</body>
</html>

templates/user_center_info.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-用户中心</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜商城!</div>
			<div class="fr">
				{% if request.user.is_authenticated %}
                    <div class="login_info fl">
                        欢迎您：<em>{{ request.user.username }}</em>
                    </div>
                    <div class="user_link fl">
                        <span>|</span>
					    <a href="{% url 'goods:index' %}">回到首页</a>
					    <span>|</span>
					    <a href="{% url 'cart:show' %}">我的购物车</a>
					    <span>|</span>
					    <a href="{% url 'user:order' 1 %}">我的订单</a>
                        <span>|</span>
                        <a href="{% url 'user:logout' %}">退出登录</a>
				    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">登录</a>
					    <span>|</span>
					    <a href="{% url 'user:register' %}">注册</a>
                    </div>
				{% endif %}
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" id="search_keywords" name="keywords" placeholder="搜索商品">
            <input type="button" class="input_btn fr" id="jsSearchBtn" name="search" value="搜索">
		</div>		
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:users' %}" class="active">· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
                            {% if address %}
                                <li><span>联系方式：</span>{{ address.phone }}</li>
                                <li><span>联系地址：</span>{{ address.addr }}</li>
                            {% else %}
                                <li><span>联系方式：</span>无默认联系方式</li>
							    <li><span>收货地址：</span>无默认收货地址</li>
                            {% endif %}
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                    {% for goods in goods_li %}
                        <li>
                            <a href="{% url 'goods:detail' goods.id %}"><img src="{{ goods.image.url }}"></a>
                            <h4><a href="detail.html">{{ goods.name }}</a></h4>
                            <div class="operate">
                                <span class="prize">￥{{ goods.price }}</span>
                                <span class="unit">{{ goods.price }}/{{ goods.unite }}</span>
{#                                <a href="#" class="add_goods" title="加入购物车"></a>#}
                                <a href="javascript:;" class="add_goods" id="add_cart" sku_id="{{ goods.id }}" title="加入购物车"></a>
                                {% csrf_token %}
                            </div>
                        </li>
                    {% endfor %}
			        </ul>
		</div>
		</div>
	</div>


	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>天天生鲜商城系统</p>
	</div>

    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/search.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/add-goods.js' %}"></script>

</body>
</html>

templates/user_center_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>天天生鲜-用户中心</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
</head>
<body>
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜商城!</div>
			<div class="fr">
				{% if request.user.is_authenticated %}
                    <div class="login_info fl">
                        欢迎您：<em>{{ request.user.username }}</em>
                    </div>
                    <div class="user_link fl">
                        <span>|</span>
					    <a href="{% url 'goods:index' %}">回到首页</a>
                        <span>|</span>
					    <a href="{% url 'user:users' %}">用户中心</a>
					    <span>|</span>
					    <a href="{% url 'cart:show' %}">我的购物车</a>
                        <span>|</span>
                        <a href="{% url 'user:logout' %}">退出登录</a>
				    </div>
                {% else %}
                    <div class="login_btn fl">
                        <a href="{% url 'user:login' %}">登录</a>
					    <span>|</span>
					    <a href="{% url 'user:register' %}">注册</a>
                    </div>
				{% endif %}
			</div>
		</div>		
	</div>

	<div class="search_bar clearfix">
		<a href="{% url 'goods:index' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;用户中心</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" id="search_keywords" name="keywords" placeholder="搜索商品">
            <input type="button" class="input_btn fr" id="jsSearchBtn" name="search" value="搜索">
		</div>
	</div>

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'user:users' %}">· 个人信息</a></li>
				<li><a href="{% url 'user:order' 1 %}" class="active">· 全部订单</a></li>
				<li><a href="{% url 'user:address' %}">· 收货地址</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
            <h3 class="common_title2">全部订单</h3>
            {% for order in order_page %}
                <ul class="order_list_th w978 clearfix">
                    <li class="col01">{{ order.create_time }}</li>
                    <li class="col02">订单号：{{ order.order_id }}</li>
                    <li class="col02 stress"><b>{{order.get_order_status_display }}</b></li>
                </ul>

                <table class="order_list_table w980">
                    <tbody>
                        <tr>
                            <td width="55%">
                                {% for order_sku in order.order_sku %}
                                    <ul class="order_goods_list clearfix">
                                        <a href="{% url 'goods:detail' order_sku.sku.id %}"><li class="col01"><img src="{{ order_sku.sku.image.url }}"></li></a>
                                        <li class="col02">{{ order_sku.sku.name }}<em>{{ order_sku.price }}元/{{ order_sku.sku.unite }}</em></li>
                                        <li class="col03">数量：{{ order_sku.count }}</li>
                                        <li class="col04">{{ order_sku.amount }}元</li>
                                    </ul>
                                {% endfor %}
                            </td>
                            {% csrf_token %}
                            <td width="15%">{{ order.total_price|add:order.transit_price }}(含运费:{{ order.transit_price }})元</td>
                            <td width="15%">{{ order.get_order_status_display }}</td>
                            <td width="15%"><a href="#" order_id="{{ order.order_id }}" status="{{ order.order_status }}" class="oper_btn">去付款</a></td>
                        </tr>
                    </tbody>
                </table>
            {% endfor %}

            <div class="pagenation">
                {% if order_page.has_previous %}
                    <a href="{% url 'user:order' order_page.previous_page_number %}">上一页</a>
                {% endif %}
                {% for pindex in pages %}
                    {% if pindex == order_page.number %}
                        <a href="{% url 'user:order' pindex %}" class="active success">{{ pindex }}</a>
                    {% else %}
                        <a href="{% url 'user:order' pindex %}">{{ pindex }}</a>
                    {% endif %}
                {% endfor %}
                {% if order_page.has_next %}
                    <a href="{% url 'user:order' order_page.next_page_number %}">下一页></a>
                {% endif %}
            </div>
		</div>
	</div>

	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>天天生鲜商城系统</p>
	</div>

<script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/search.js' %}"></script>
<script type="text/javascript">
    $('.oper_btn').each(function () {
        // 获取支付状态
        status = $(this).attr('status');
        if (status == 1){
            $(this).text('去支付')
        }
        else if (status == 4){
            $(this).text('去评价')
        }
        else if (status == 5){
            $(this).text('已完成')
        }
    });

    $('.oper_btn').click(function () {
        // 获取status
        status = $(this).attr('status');
        // 获取订单id
        order_id = $(this).attr('order_id');
        if (status == 1){
            // 进行支付
            csrf = $('input[name="csrfmiddlewaretoken"]').val();
            // 组织参数
            params = {'order_id':order_id, 'csrfmiddlewaretoken':csrf};
            // 发起ajax post请求，访问/order/pay, 传递参数:order_id
            $.post('/order/pay', params, function (data) {
                if (data.res == 3){
                    // 引导用户到支付页面
                    window.open(data.pay_url);
                    // 浏览器访问/order/check, 获取支付交易的结果
                    // ajax post 传递参数:order_id
                    $.post('/order/check', params, function (data){
                        if (data.res == 3){
                            alert('支付成功');
                            // 刷新页面
                            location.reload()
                        }
                        else{
                            alert(data.errmsg)
                        }
                    })
                }
                else{
                    alert(data.errmsg)
                }
            })
        }
        else if (status == 4){
            // 其他情况
            // 跳转到评价页面
            location.href = '/order/comment/'+order_id
        }
    })
</script>
	
</body>
</html>